/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-04-27 11:03:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Sign Up</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("*, *:before, *:after {\r\n");
      out.write("\t-moz-box-sizing: border-box;\r\n");
      out.write("\t-webkit-box-sizing: border-box;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: 'Nunito', sans-serif;\r\n");
      out.write("\tcolor: #384047;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmax-width: 300px;\r\n");
      out.write("\tmargin: 10px auto;\r\n");
      out.write("\tpadding: 10px 20px;\r\n");
      out.write("\tbackground: #f4f7f8;\r\n");
      out.write("\tborder-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tmargin: 0 0 30px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], input[type=\"password\"], input[type=\"date\"], input[type=\"datetime\"],\r\n");
      out.write("\tinput[type=\"email\"], input[type=\"number\"], input[type=\"search\"], input[type=\"tel\"],\r\n");
      out.write("\tinput[type=\"time\"], input[type=\"url\"], textarea, select {\r\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.1);\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbackground-color: #e8eeef;\r\n");
      out.write("\tcolor: #8a97a0;\r\n");
      out.write("\tbox-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"radio\"], input[type=\"checkbox\"] {\r\n");
      out.write("\tmargin: 0 4px 8px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("\tpadding: 6px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\tborder-radius: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\tpadding: 19px 39px 18px 39px;\r\n");
      out.write("\tcolor: #FFF;\r\n");
      out.write("\tbackground-color: #4bc970;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tborder: 1px solid #3ac162;\r\n");
      out.write("\tborder-width: 1px 1px 3px;\r\n");
      out.write("\tbox-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("fieldset {\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("legend {\r\n");
      out.write("\tfont-size: 1.4em;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmargin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label.light {\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".number {\r\n");
      out.write("\tbackground-color: #5fcf80;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\twidth: 30px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 0.8em;\r\n");
      out.write("\tmargin-right: 4px;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-shadow: 0 1px 0 rgba(255, 255, 255, 0.2);\r\n");
      out.write("\tborder-radius: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (min-width: 480px) {\r\n");
      out.write("\tform {\r\n");
      out.write("\t\tmax-width: 480px;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Sign Up Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/normalize.css\">\r\n");
      out.write("<link href='https://fonts.googleapis.com/css?family=Nunito:400,300'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h1>Registration</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>\r\n");
      out.write("\t\t\t\t<span class=\"number\">1</span>Your basic info\r\n");
      out.write("\t\t\t</legend>\r\n");
      out.write("\t\t\t<label for=\"name\">Name:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"name\" name=\"uname\"> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label for=\"password\">Password:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"password\"name=\"password\">\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label for=\"role\">User Role:</label> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<select id=\"role\" name=\"role\">\r\n");
      out.write("                 <option value=\"Lecturer\">Lecturer</option>\r\n");
      out.write("\t\t\t\t <option value=\"User\">User</option>\r\n");
      out.write("\t\t\t</select> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label for=\"name\">Personal Address:</label>\r\n");
      out.write("\t\t\t<textarea id=\"personaladdress\" name=\"personaladdress\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label>Sex:</label> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"under_13\" value=\"male\"\r\n");
      out.write("\t\t\t\tname=\"sex\"><label for=\"under_13\" class=\"light\">Male</label><br>\r\n");
      out.write("\t\t\t<input type=\"radio\" id=\"over_13\" value=\"female\" name=\"sex\"><label\r\n");
      out.write("\t\t\t\tfor=\"over_13\" class=\"light\">Female</label> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t   <label for=\"mail\">Email:</label>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"mail\" name=\"user_email\">  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label for=\"dob\">DOB:</label> \r\n");
      out.write("\t\t\t<input type=\"text\" id=\"dob\" name=\"dob\">\r\n");
      out.write("\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\t\t\t<legend>\r\n");
      out.write("\t\t\t\t<span class=\"number\">2</span>Your profile\r\n");
      out.write("\t\t\t</legend>\r\n");
      out.write("\t\t\t<label for=\"bio\">Biography:</label>\r\n");
      out.write("\t\t\t<textarea id=\"bio\" name=\"user_bio\"></textarea>\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<fieldset>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<label>Interests:</label> <input type=\"checkbox\" id=\"development\"\r\n");
      out.write("\t\t\t\tvalue=\"interest_development\" name=\"user_interest\"><label\r\n");
      out.write("\t\t\t\tclass=\"light\" for=\"development\">Development</label><br> <input\r\n");
      out.write("\t\t\t\ttype=\"checkbox\" id=\"design\" value=\"interest_design\"\r\n");
      out.write("\t\t\t\tname=\"user_interest\"><label class=\"light\" for=\"design\">Design</label><br>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"business\" value=\"interest_business\"\r\n");
      out.write("\t\t\t\tname=\"user_interest\"><label class=\"light\" for=\"business\">Business</label>\r\n");
      out.write("\r\n");
      out.write("\t\t</fieldset>\r\n");
      out.write("\t\t<button type=\"submit\">Register</button>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
