/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-04-29 07:36:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class request_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("        <title>Login Form</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\n");
      out.write("        <!--        <link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.min.css\">-->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--For Plugins external css-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/plugins.css\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/roboto-webfont.css\" />\n");
      out.write("\n");
      out.write("        <!--Theme custom css -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">\n");
      out.write("\n");
      out.write("        <!--Theme Responsive css-->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/responsive.css\" />\n");
      out.write("\n");
      out.write("        <script src=\"assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <script type=\"text/javascript\" src=\"JS/jquery-1.4.2.min.js\"></script>\n");
      out.write("<script src=\"JS/autocomplete-0.3.0.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script language=\"javascript\">\n");
      out.write("\n");
      out.write("$(\"#keyword\").keypress(function ()\n");
      out.write("{\n");
      out.write("\tdebugger;\n");
      out.write("\tautocomplete(\"list.jsp\");\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("input[type=\"text\"] {\n");
      out.write("\tbackground: rgba(255, 255, 255, 0.1);\n");
      out.write("\tborder: none;\n");
      out.write("\tfont-size: 16px;\n");
      out.write("\theight: auto;\n");
      out.write("\tmargin: 0;\n");
      out.write("\toutline: 0;\n");
      out.write("\tpadding: 15px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tbackground-color: #e8eeef;\n");
      out.write("\tcolor: #8a97a0;\n");
      out.write("\tbox-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;\n");
      out.write("\tmargin-bottom: 30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("submit {\n");
      out.write("\tpadding: 19px 39px 18px 39px;\n");
      out.write("\tcolor: #FFF;\n");
      out.write("\tbackground-color: #4bc970;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tfont-style: normal;\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder: 1px solid #3ac162;\n");
      out.write("\tborder-width: 1px 1px 3px;\n");
      out.write("\tbox-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".autocomplete\n");
      out.write("{\n");
      out.write(" \tpadding: 19px 39px 18px 39px;\n");
      out.write("\tcolor: #FFF;\n");
      out.write("\tbackground-color: #4bc970;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("\ttext-align: center;\n");
      out.write("\tfont-style: normal;\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tborder: 1px solid #3ac162;\n");
      out.write("\tborder-width: 1px 1px 3px;\n");
      out.write("\tbox-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.rawgit.com/LeaVerou/awesomplete/gh-pages/awesomplete.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("   \n");
      out.write("\n");
      out.write("\t\n");
      out.write("    \n");
      out.write("\t<!--Home page style-->\n");
      out.write("\t<header id=\"home\" class=\"home\">\n");
      out.write("\t<div class=\"overlay-fluid-block\">\n");
      out.write("\t\t<div class=\"container text-center\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"home-wrapper\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1\">\n");
      out.write("\t\t\t\t\t\t<div class=\"home-content\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<center>\n");
      out.write("\n");
      out.write("<pre><a href=\"editor.jsp\">Back</a>        <a href=\"index.html\">Logout</a> </pre>\n");
      out.write("\n");
      out.write("<table border=\"1\">\n");
      out.write("    <tr>\n");
      out.write("        <th>File Name</th><th>Keywords</th><th> Email  </th><th>File Id </th>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write(" ");
	
    Class.forName("com.mysql.cj.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/learningframework", "root", "rootqwer");
	Statement stmt = con.createStatement();
	ResultSet rs = stmt.executeQuery("Select * from learningobjects1");
	
	while(rs.next())
        {
           String fname= rs.getString("filename");
            String key=rs.getString("keyword");
           String name = rs.getString("email");
            String fileid = rs.getString("id");
           
        
        

      out.write("\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("    <td>");
      out.print(fname);
      out.write("</td><td>");
      out.print(key);
      out.write(" </td><td>  ");
      out.print(name);
      out.write("  </td><td>  ");
      out.print(fileid);
      out.write("  </td>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <td>  <form action=\"edownload12\" method =\"get\">\n");
      out.write("                             \n");
      out.write("                                     <input type=\"hidden\" value=\"");
      out.print(name);
      out.write("\" name=\"lat\">\n");
      out.write("                                <input type=\"hidden\" value=\"");
      out.print(fileid);
      out.write("\" name=\"lng\">\n");
      out.write("                                <input type=\"submit\" value=\"Download\">\n");
      out.write("                              \n");
      out.write("                                 </form>\n");
      out.write("    </td>\n");
      out.write("    \n");
      out.write("    <td>  <form action=\"accept\" method =\"get\">\n");
      out.write("                             \n");
      out.write("            \n");
      out.write("              <input type=\"hidden\" value=\"");
      out.print(fname);
      out.write("\" name=\"f1\">\n");
      out.write("                                <input type=\"hidden\" value=\"");
      out.print(key);
      out.write("\" name=\"key\">\n");
      out.write("                               \n");
      out.write("                                     <input type=\"hidden\" value=\"");
      out.print(name);
      out.write("\" name=\"lat\">\n");
      out.write("                                <input type=\"hidden\" value=\"");
      out.print(fileid);
      out.write("\" name=\"lng\">\n");
      out.write("                                <input type=\"submit\" value=\"Accept\">\n");
      out.write("                              \n");
      out.write("                                 </form>\n");
      out.write("    </td>\n");
      out.write("    \n");
      out.write("    <td>  <form action=\"reject\" method =\"get\">\n");
      out.write("                             \n");
      out.write("                                     <input type=\"hidden\" value=\"");
      out.print(name);
      out.write("\" name=\"lat\">\n");
      out.write("                                <input type=\"hidden\" value=\"");
      out.print(fileid);
      out.write("\" name=\"lng\">\n");
      out.write("                                <input type=\"submit\" value=\"Reject\">\n");
      out.write("                              \n");
      out.write("                                 </form>\n");
      out.write("    </td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("\n");

}
    
      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("</center>\n");
      out.write("\n");
      out.write("\t<script src=\"assets/js/vendor/jquery-1.11.2.min.js\"></script>\n");
      out.write("\t<script src=\"assets/js/vendor/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script src=\"assets/js/plugins.js\"></script>\n");
      out.write("\t<script src=\"assets/js/modernizr.js\"></script>\n");
      out.write("\t<script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script src=\"js/index.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdn.rawgit.com/LeaVerou/awesomplete/gh-pages/awesomplete.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
