/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2021-04-29 08:02:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;

public final class User_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("        <title>Login Form</title>\r\n");
      out.write("        <meta name=\"description\" content=\"\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"apple-touch-icon\" href=\"apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("        <!--        <link rel=\"stylesheet\" href=\"assets/css/bootstrap-theme.min.css\">-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!--For Plugins external css-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/plugins.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/roboto-webfont.css\" />\r\n");
      out.write("\r\n");
      out.write("        <!--Theme custom css -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("        <!--Theme Responsive css-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/responsive.css\" />\r\n");
      out.write("\r\n");
      out.write("        <script src=\"assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"JS/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("        <script src=\"JS/autocomplete-0.3.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("            $(\"#keyword\").keypress(function ()\r\n");
      out.write("            {\r\n");
      out.write("                debugger;\r\n");
      out.write("                autocomplete(\"list.jsp\");\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("\r\n");
      out.write("            .az\r\n");
      out.write("            {\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                bottom:-100%;\r\n");
      out.write("                border: 2px solid black;\r\n");
      out.write("                background-color: grey;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            input[type=\"text\"] {\r\n");
      out.write("                background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("                border: none;\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                height: auto;\r\n");
      out.write("                margin: 0;\r\n");
      out.write("                outline: 0;\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                background-color: #e8eeef;\r\n");
      out.write("                color: #8a97a0;\r\n");
      out.write("                box-shadow: 0 1px 0 rgba(0, 0, 0, 0.03) inset;\r\n");
      out.write("                margin-bottom: 30px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            submit {\r\n");
      out.write("                padding: 19px 39px 18px 39px;\r\n");
      out.write("                color: #FFF;\r\n");
      out.write("                background-color: #4bc970;\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                font-style: normal;\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                border: 1px solid #3ac162;\r\n");
      out.write("                border-width: 1px 1px 3px;\r\n");
      out.write("                box-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;\r\n");
      out.write("                margin-bottom: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .autocomplete\r\n");
      out.write("            {\r\n");
      out.write("                padding: 19px 39px 8px 39px;\r\n");
      out.write("                color: #FFF;\r\n");
      out.write("                background-color: #4bc970;\r\n");
      out.write("                font-size: 18px;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                font-style: normal;\r\n");
      out.write("                border-radius: 5px;\r\n");
      out.write("                width: 200%;\r\n");
      out.write("                border: 1px solid #3ac162;\r\n");
      out.write("                border-width: 1px 1px 3px;\r\n");
      out.write("                box-shadow: 0 -1px 0 rgba(255, 255, 255, 0.1) inset;\r\n");
      out.write("                margin-bottom: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.rawgit.com/LeaVerou/awesomplete/gh-pages/awesomplete.css\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("        ");

            String userID = request.getAttribute("userName").toString();
            System.out.println("User ID = " + userID);
            session.setAttribute("user_id", userID);
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");


            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/learningframework", "root", "rootqwer");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("Select keyword from keywords ORDER BY pi ASC");

            List li = new ArrayList();

            while (rs.next()) {
                li.add(rs.getString(1));
            }

        
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            ArrayList ad = new ArrayList();
            ResultSet rs1 = stmt.executeQuery("Select keyword from keywords ORDER BY pi desc");
            while (rs1.next()) {
                ad.add(rs1.getString("keyword"));

                System.out.println(rs1.getString("keyword"));
            }



        
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("        \r\n");
      out.write("            function next_page_dj(){\r\n");
      out.write("           \r\n");
      out.write("                var sp=document.getElementById(\"spid\").value;\r\n");
      out.write("              \r\n");
      out.write("                window.location=\"next?cpage=LEDRiser&vendor=\"+vendor+\"&cp=\"+cp+\"&sp=\"+sp+\"&profit=\"+profit+\"&quantity=\"+c;\r\n");
      out.write("           \r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("            function cal(){\r\n");
      out.write("            \r\n");
      out.write("                var sp=document.getElementById(\"spid\").value;\r\n");
      out.write("                var profit=sp;\r\n");
      out.write("            \r\n");
      out.write("                document.getElementById(\"profitid\").value=profit;\r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("            function check(){\r\n");
      out.write("            \r\n");
      out.write("       \r\n");
      out.write("                alert(c);\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </script>\r\n");
      out.write("        <!--Home page style-->\r\n");
      out.write("    <header id=\"home\" class=\"home\">\r\n");
      out.write("        <div class=\"overlay-fluid-block\">\r\n");
      out.write("            <div class=\"container text-center\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"home-wrapper\">\r\n");
      out.write("                        <div class=\"col-md-10 col-md-offset-1\">\r\n");
      out.write("                            <div class=\"home-content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("<div class=\"az\">\r\n");
      out.write("                                       \r\n");
      out.write("                                        <table style=\"color:black\" align=\"center\" cellpadding=\"40px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"SearchServlet\" method=\"post\">\r\n");
      out.write("    <tr>\r\n");
      out.write("                                                    <td> Most Searched Keywords\r\n");
      out.write("                                                        <select style=\"color:black\" name=\"search\" id=\"spid\">\r\n");
      out.write("                                            ");

                                                for (int i = 0; i < 16; i++) {

                                            
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            \r\n");
      out.write("                                            <option value=\"");
      out.print(ad.get(i));
      out.write('"');
      out.write('>');
      out.print(ad.get(i));
      out.write(" </option>     \r\n");
      out.write("                                                        \r\n");
      out.write("       \r\n");
      out.write("                                                    <!--                                                    <td>  <input  type=\"submit\" value=\"search\" style=\"color:black\">-->\r\n");
      out.write("\r\n");
      out.write("                                                    \r\n");
      out.write("                                           \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            ");

                                                }

                                            
      out.write("\r\n");
      out.write("                                                        </select>\r\n");
      out.write("                                            </td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                             \r\n");
      out.write(" </form>\r\n");
      out.write("                                                        <form action=\"SearchServlet\" method=\"post\">\r\n");
      out.write("                                        \r\n");
      out.write("                                                            <td> <h3 style=\"color:blue\">Search File :</h3></td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input class=\"autocomplete\" id=\"profitid\" type=\"text\" name=\"search\" onclick=\"return cal();\"> \r\n");
      out.write("                                        <input\r\n");
      out.write("                                            type=\"submit\" value=\"search\" onclick=\"return next_page_dj();\" /></td>\r\n");
      out.write("                                           </tr>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </form>\r\n");
      out.write("                                        </table>\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"scrollup\">\r\n");
      out.write("        <a href=\"#\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/js/vendor/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/js/plugins.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/modernizr.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/index.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"https://cdn.rawgit.com/LeaVerou/awesomplete/gh-pages/awesomplete.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      \r\n");
      out.write("        var input = document.getElementById(\"keyword\");\r\n");
      out.write("      \r\n");
      out.write("        var awesomplete = new Awesomplete(input , {list:\"");
      out.print(li);
      out.write("\"});\r\n");
      out.write("         \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
